### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by divios** [WesJD/AnvilGUI#129]
Hi, someone reported me this bug on my plugin. I tested it a couple of times and it neves happens in my local. Reading the full error i found out that another plugin appears on it (cosmic vaults), so now i'm confused if somehow that plugin is causing the error or is just a bug from the anvilGUI. This is the error https://hastebin.com/ujasipurik.properties

**Comment by portlek** [comment]
could you share your pom/gradle file?

**Comment by Sytm** [comment]
Looks like the following to me:

An older AnvilGUI version has been shaded into Cosmic_Vaults-2.0.6 (which does not have the method .itemLeft() ) without relocating it (like a very big no no for Spigot plugins because this can happen).
This plugin has been loaded first.
```
Caused by: java.lang.NoSuchMethodError: net/wesjd/anvilgui/AnvilGUI$Builder.itemLeft(Lorg/bukkit/inventory/ItemStack;)Lnet/wesjd/anvilgui/AnvilGUI$Builder; (loaded from file:/home/amp/.ampdata/instances/KarmaGamingSkyblock/Minecraft/plugins/Cosmic_Vaults-2.0.6.jar by org.bukkit.plugin.java.PluginClassLoader@9502987b)
```
Your plugin has a newer version of AnvilGUI shaded into it (also without relocating it apparently) which has the .itemLeft() method-
```
called from class io.github.divios.dailyrandomshop.Listeners.dailyGuiSettingsListener (loaded from file:/home/amp/.ampdata/instances/KarmaGamingSkyblock/Minecraft/plugins/DailyRandomShop-1.13.3.jar by org.bukkit.plugin.java.PluginClassLoader@7de2eda0)
```
but because it has been loaded after the other plugin, the newer AnvilGUI classes are not loaded.

So at runtime, the JVM could not find the itemLeft() method because it was simply not there.

Possible solution:
[If you use Maven, configure the maven shade plugin to relocate the classes to a package in your plugin.](https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html)

[If you use Gradle, configure the gradle shadow plugin to relocate the classes to a package in your plugin.](https://imperceptiblethoughts.com/shadow/configuration/relocation/)

**Comment by divios** [comment]
Hi! This is my pom https://hastebin.com/emimetafuq.xml, at least the shade part, I am relatively new to this and maybe i'm doing something wrong

**Comment by divios** [comment]
oh ups, i don't know what was i thinkg, just realize that i didn't reshade it hehe my bad

**Comment by divios** [comment]
Sorry for being annoying but just to make sure, does this make sense? https://hastebin.com/fipanazute.xml

**Comment by Sytm** [comment]
The AnvilGUI related part should work out

**Comment by divios** [comment]
Alright thanks for all!
