### ISSUE TITLE
enterInput consumer.

### ISSUE THREAD

**Issue by UsainSrht** [WesJD/AnvilGUI#231]
idk if this is possible but I want to run a function -change the title or smth- when the player types a character in anvil gui. This is possible with physical anvil gui's with `org.bukkit.event.inventory.PrepareAnvilEvent`

**Comment by mastercake10** [comment]
Its possible, but only for mc versions => 1.9-R0.1. So this feature would not work on 1.7 and 1.8 since there is no event / packet present for changing the name of an item in the anvil. This project aims to support all versions from 1.7, so I don't know if its a good idea to add this.

**Comment by UsainSrht** [comment]
I mean who uses those 8 years old versions anymore? I'd appreciate if you could add this feature for supported versions.

**Comment by mastercake10** [comment]
For my plugins, about 5% of the servers are still using 1.8.9. They do it on purpose I think, better performance and stuff.

**Comment by WesJD** [comment]
I think it is still valid to add features even if they don't support older versions. This is definitely and interesting idea but I will not have any time to implement it for some time. If you are interested in adding it in, I highly recommend making a PR!

**Comment by WesJD** [comment]
You can see my comments on #232 on why we aren't moving forward with this feature. Overall it feels very clunky to implement and I really don't see a lot of support behind needing to add it. Feels like it could be a cool addition but we can't limit other developer's usage of the library in order to support this cleanly for the user.
