### ISSUE TITLE
Adventure Components + MiniMessage support

### ISSUE THREAD

**Issue by UsainSrht** [WesJD/AnvilGUI#233]
Ability to use TextComponents as well as minimessage formatting in item names and title.

**Comment by WesJD** [comment]
To add on to the above comment, for the GUI title, the removal of the text-based methods doesn't solve the problem.

Overall, this is difficult to solve because manually including Adventure into this library would cause it to conflict with the package names provided in Paper. It would leave developers having to deal with Adventure potentially being included multiple times on their server.
