### ISSUE TITLE
Addvoid response

### ISSUE THREAD

**Issue by TheSilentPro** [WesJD/AnvilGUI#234]
Currently if you have to either: keep the inventory open to change the text OR close it OR open another inventory.
An option to do nothing would be nice. maybe something like AnvilGUI.Response.void(); and it does nothing

**Comment by WesJD** [comment]
Have you tried just returning the text that they wrote?

**Comment by TheSilentPro** [comment]
Well Response#text changes the items name afaik, it still keeps the inventory open. 
For example:
If i wanted to run a command that opens an inventory when the user clicks on the result it's impossible since the anvilgui is still open and returning Response#close would close the newly opened inventory.

**Comment by WesJD** [comment]
I am confused then by your request - a void response _would_ keep the inventory open. So, `AnvilGUI.Response.text(input)` would just do absolutely nothing when they click the button and keep it open. If you need to open an inventory, you can just use `AnvilGUI.Response.openInventory(inventory)` in order to achieve that.

**Comment by WesJD** [comment]
If you need to run a command to open an inventory, just use the Bukkit scheduler to run a task one tick later to run the command. There is really no way around AnvilGUI closing the next inventory you open with how it is designed.
