### ISSUE TITLE
onClose issue

### ISSUE THREAD

**Issue by Fedee0** [WesJD/AnvilGUI#265]
`onClose` is also executed if the user clicks on the item to confirm the entered text.

I don't know if it is supposed to be this way, if so how should I make it so that it is only executed if the user has closed the gui with the `Escape` key?

**Comment by Sytm** [comment]
Clicking and closing the GUI are two different things and should be handled differently (I personally make use of that).

But if you need to make sure that your code in onClose is only run if the player closed it manually you could do something like this:
```java
AtomicBoolean clicked = new AtomicBoolean(false);
new AnvilGUI.Builder()
        .plugin(plugin)
        .text("Hello")
        .onClick((slot, state) -> {
            clicked.set(true);
            return Collections.singletonList(AnvilGUI.ResponseAction.close());
        }).onClose(state -> {
            if (clicked.get()) {
                return;
            }
            player.sendMessage("You shouldn't close the GUI");
        }).open(player);
```
Sadly Java requires the use of an atomic boolean because the variables accessed by lambdas need to be effectively final

**Comment by Fedee0** [comment]
@Sytm Thank you very much, this helped me a lot
